name: trader-crawler
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - sqlalchemy
  - pydantic
  - python-dotenv
  - selenium
  - pip:
      - webdriver-manager
      - pymysql
