upstream backend_cluster {
    server 127.0.0.1:8000;
    server 127.0.0.1:8001;
}

upstream backend_websocket_cluster {
    ip_hash;
    server 127.0.0.1:8000;
    server 127.0.0.1:8001;
}

map $http_upgrade $backend_upstream {
    default   backend_cluster;
    websocket backend_websocket_cluster;
}

server {
    listen 80;
    server_name beta.trader-bot.org;

    client_max_body_size 1m;

    access_log off;
    error_log /var/log/nginx/trader-bot-beta.log error;

    location /api/ {
        proxy_pass http://$backend_upstream;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header X-Request-ID $request_id;

        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
    }

    location /health {
        return 204;
    }
}