services:
  postgres:
    image: postgres:18.3
    container_name: trader-bot-ctr-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - trader-bot-dev-vol-db:/var/lib/postgresql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  trader-bot-dev-vol-db:
    name: trader-bot-dev-vol-db
