"""
Revision: 648288991eae
Version: v0.5.0a0
Parent:
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "648288991eae"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("subscription_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.Column("billing_key", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.discord_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subscription_id"),
        sa.UniqueConstraint("guild_id"),
    )
    op.create_table(
        "payment",
        sa.Column("payment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("payment_key", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscription.subscription_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("payment_id"),
        sa.UniqueConstraint("order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment")
    op.drop_table("subscription")
    # ### end Alembic commands ###
