"""
Revision: 98d2449808d5
Version: v0_5_3a0
Parent: 41e6b9d89995
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "98d2449808d5"
down_revision: str | Sequence[str] | None = "41e6b9d89995"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("billing_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "payment", "billing", ["billing_id"], ["billing_id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_column("payment", "billing_id")
    # ### end Alembic commands ###
