"""
Revision: cf1ac2f93fb3
Version: v0.5.0a0
Parent:
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "cf1ac2f93fb3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing",
        sa.Column("billing_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("billing_key", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.discord_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("billing_id"),
    )
    op.create_table(
        "payment",
        sa.Column("payment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("payment_key", sa.Text(), nullable=True),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"], ["guild.discord_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.discord_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("payment_id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "subscription",
        sa.Column("subscription_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("billing_id", sa.Integer(), nullable=True),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_id"], ["billing.billing_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["guild.discord_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subscription_id"),
        sa.UniqueConstraint("guild_id"),
    )
    op.create_unique_constraint(None, "preset_member", ["preset_id", "member_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "preset_member", type_="unique")
    op.drop_table("subscription")
    op.drop_table("payment")
    op.drop_table("billing")
    # ### end Alembic commands ###
