/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PatchRouteImport } from './routes/patch'
import { Route as AnnouncementRouteImport } from './routes/announcement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuildGuildIdMemberRouteImport } from './routes/guild/$guildId/member'
import { Route as AuthLoginCallbackRouteImport } from './routes/auth/login/callback'
import { Route as GuildGuildIdPresetPresetIdRouteImport } from './routes/guild/$guildId/preset/$presetId'
import { Route as GuildGuildIdPresetPresetIdIndexRouteImport } from './routes/guild/$guildId/preset/$presetId/index'
import { Route as GuildGuildIdPresetPresetIdAuctionAuctionIdRouteImport } from './routes/guild/$guildId/preset/$presetId/auction/$auctionId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchRoute = PatchRouteImport.update({
  id: '/patch',
  path: '/patch',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementRoute = AnnouncementRouteImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildGuildIdMemberRoute = GuildGuildIdMemberRouteImport.update({
  id: '/guild/$guildId/member',
  path: '/guild/$guildId/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginCallbackRoute = AuthLoginCallbackRouteImport.update({
  id: '/auth/login/callback',
  path: '/auth/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildGuildIdPresetPresetIdRoute =
  GuildGuildIdPresetPresetIdRouteImport.update({
    id: '/guild/$guildId/preset/$presetId',
    path: '/guild/$guildId/preset/$presetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuildGuildIdPresetPresetIdIndexRoute =
  GuildGuildIdPresetPresetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GuildGuildIdPresetPresetIdRoute,
  } as any)
const GuildGuildIdPresetPresetIdAuctionAuctionIdRoute =
  GuildGuildIdPresetPresetIdAuctionAuctionIdRouteImport.update({
    id: '/auction/$auctionId',
    path: '/auction/$auctionId',
    getParentRoute: () => GuildGuildIdPresetPresetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRoute
  '/patch': typeof PatchRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login/callback': typeof AuthLoginCallbackRoute
  '/guild/$guildId/member': typeof GuildGuildIdMemberRoute
  '/guild/$guildId/preset/$presetId': typeof GuildGuildIdPresetPresetIdRouteWithChildren
  '/guild/$guildId/preset/$presetId/': typeof GuildGuildIdPresetPresetIdIndexRoute
  '/guild/$guildId/preset/$presetId/auction/$auctionId': typeof GuildGuildIdPresetPresetIdAuctionAuctionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRoute
  '/patch': typeof PatchRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login/callback': typeof AuthLoginCallbackRoute
  '/guild/$guildId/member': typeof GuildGuildIdMemberRoute
  '/guild/$guildId/preset/$presetId': typeof GuildGuildIdPresetPresetIdIndexRoute
  '/guild/$guildId/preset/$presetId/auction/$auctionId': typeof GuildGuildIdPresetPresetIdAuctionAuctionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRoute
  '/patch': typeof PatchRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login/callback': typeof AuthLoginCallbackRoute
  '/guild/$guildId/member': typeof GuildGuildIdMemberRoute
  '/guild/$guildId/preset/$presetId': typeof GuildGuildIdPresetPresetIdRouteWithChildren
  '/guild/$guildId/preset/$presetId/': typeof GuildGuildIdPresetPresetIdIndexRoute
  '/guild/$guildId/preset/$presetId/auction/$auctionId': typeof GuildGuildIdPresetPresetIdAuctionAuctionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcement'
    | '/patch'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login/callback'
    | '/guild/$guildId/member'
    | '/guild/$guildId/preset/$presetId'
    | '/guild/$guildId/preset/$presetId/'
    | '/guild/$guildId/preset/$presetId/auction/$auctionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcement'
    | '/patch'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login/callback'
    | '/guild/$guildId/member'
    | '/guild/$guildId/preset/$presetId'
    | '/guild/$guildId/preset/$presetId/auction/$auctionId'
  id:
    | '__root__'
    | '/'
    | '/announcement'
    | '/patch'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login/callback'
    | '/guild/$guildId/member'
    | '/guild/$guildId/preset/$presetId'
    | '/guild/$guildId/preset/$presetId/'
    | '/guild/$guildId/preset/$presetId/auction/$auctionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementRoute: typeof AnnouncementRoute
  PatchRoute: typeof PatchRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthLoginCallbackRoute: typeof AuthLoginCallbackRoute
  GuildGuildIdMemberRoute: typeof GuildGuildIdMemberRoute
  GuildGuildIdPresetPresetIdRoute: typeof GuildGuildIdPresetPresetIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch': {
      id: '/patch'
      path: '/patch'
      fullPath: '/patch'
      preLoaderRoute: typeof PatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement': {
      id: '/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof AnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild/$guildId/member': {
      id: '/guild/$guildId/member'
      path: '/guild/$guildId/member'
      fullPath: '/guild/$guildId/member'
      preLoaderRoute: typeof GuildGuildIdMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/callback': {
      id: '/auth/login/callback'
      path: '/auth/login/callback'
      fullPath: '/auth/login/callback'
      preLoaderRoute: typeof AuthLoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild/$guildId/preset/$presetId': {
      id: '/guild/$guildId/preset/$presetId'
      path: '/guild/$guildId/preset/$presetId'
      fullPath: '/guild/$guildId/preset/$presetId'
      preLoaderRoute: typeof GuildGuildIdPresetPresetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild/$guildId/preset/$presetId/': {
      id: '/guild/$guildId/preset/$presetId/'
      path: '/'
      fullPath: '/guild/$guildId/preset/$presetId/'
      preLoaderRoute: typeof GuildGuildIdPresetPresetIdIndexRouteImport
      parentRoute: typeof GuildGuildIdPresetPresetIdRoute
    }
    '/guild/$guildId/preset/$presetId/auction/$auctionId': {
      id: '/guild/$guildId/preset/$presetId/auction/$auctionId'
      path: '/auction/$auctionId'
      fullPath: '/guild/$guildId/preset/$presetId/auction/$auctionId'
      preLoaderRoute: typeof GuildGuildIdPresetPresetIdAuctionAuctionIdRouteImport
      parentRoute: typeof GuildGuildIdPresetPresetIdRoute
    }
  }
}

interface GuildGuildIdPresetPresetIdRouteChildren {
  GuildGuildIdPresetPresetIdIndexRoute: typeof GuildGuildIdPresetPresetIdIndexRoute
  GuildGuildIdPresetPresetIdAuctionAuctionIdRoute: typeof GuildGuildIdPresetPresetIdAuctionAuctionIdRoute
}

const GuildGuildIdPresetPresetIdRouteChildren: GuildGuildIdPresetPresetIdRouteChildren =
  {
    GuildGuildIdPresetPresetIdIndexRoute: GuildGuildIdPresetPresetIdIndexRoute,
    GuildGuildIdPresetPresetIdAuctionAuctionIdRoute:
      GuildGuildIdPresetPresetIdAuctionAuctionIdRoute,
  }

const GuildGuildIdPresetPresetIdRouteWithChildren =
  GuildGuildIdPresetPresetIdRoute._addFileChildren(
    GuildGuildIdPresetPresetIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementRoute: AnnouncementRoute,
  PatchRoute: PatchRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthLoginCallbackRoute: AuthLoginCallbackRoute,
  GuildGuildIdMemberRoute: GuildGuildIdMemberRoute,
  GuildGuildIdPresetPresetIdRoute: GuildGuildIdPresetPresetIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
