name: redis

services:
  redis:
    image: redis:7.0.15
    container_name: trader-bot-dev-ctr-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      sh -c "chown redis:redis /var/log/redis &&
             redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - trader-bot-dev-vol-redis:/var/log/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  trader-bot-dev-vol-redis:
    name: trader-bot-dev-vol-redis
