bind 0.0.0.0
port 6379
protected-mode no
tcp-backlog 128
timeout 0
tcp-keepalive 300

maxmemory 512mb
maxmemory-policy noeviction

save ""
appendonly no
rdbchecksum no

maxclients 100

loglevel notice
logfile "/var/log/redis/redis-server.log"
