name: CI CD Frontend

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag || github.ref }}

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: CI
        working-directory: frontend
        env:
          VITE_API_ORIGIN: https://${{ vars.EC2_HOST }}
          VITE_DISCORD_CLIENT_ID: ${{ vars.DISCORD_CLIENT_ID }}
          VITE_GUILD_INVITE_URL: ${{ vars.GUILD_INVITE_URL }}
        run: npm ci && npm run build

      - name: CD
        env:
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws s3 sync frontend/dist s3://$S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
