name: Deploy Bot

on:
  push:
    tags: ["v*"]
    paths:
      - "python/bot/**"
      - "python/shared/**"
      - "python/pyproject.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GIT
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SECRET }}
          script: |
            set -e

            cd /var/www/trader-bot
            git fetch --tags origin
            git checkout --detach "${{ github.ref_name }}"

      - name: ENV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SECRET }}
          script: |
            set -e

            cd /var/www/trader-bot
            cat << EOF > python/.env
            DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
            DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}
            APP_ORIGIN=https://${{ vars.EC2_HOST }}
            API_ORIGIN=https://${{ vars.EC2_HOST }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            RDS_INSTANCE_IDENTIFIER=${{ vars.RDS_INSTANCE_IDENTIFIER }}
            RDS_REGION=${{ vars.AWS_REGION }}
            EOF

      - name: UV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SECRET }}
          script: |
            set -e

            cd /var/www/trader-bot/python
            uv sync --frozen

      - name: PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SECRET }}
          script: |
            set -e

            cd /var/www/trader-bot/python
            pm2 reload trader-bot || pm2 start "uv run python -m bot.main" --name trader-bot

            pm2 save
