name: edge-deploy-cloudfront

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: edge-deploy-cloudfront
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ vars.EDGE_AWS_REGION }}

      - name: Invalidate
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.EDGE_CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
