name: frontend-invalidate

on:
  workflow_run:
    workflows: ["frontend-distribute", "frontend-public-distribute"]
    types: [completed]
  workflow_dispatch:
    inputs:
      tag:
        description: "Version"
        required: true

concurrency:
  group: frontend-invalidate
  cancel-in-progress: true

jobs:
  run:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Prepare
        id: prepare
        run: |
          DISTRIBUTION_ID="${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}"

          echo "distribution_id=$DISTRIBUTION_ID" >> "$GITHUB_OUTPUT"

      - name: Validate
        run: |
          DISTRIBUTION_ID="${{ steps.prepare.outputs.distribution_id }}"

          if [ -z "$DISTRIBUTION_ID" ]; then
            echo "Missing required variable: CLOUDFRONT_DISTRIBUTION_ID"
            exit 1
          fi

      - name: Run
        run: |
          CLOUDFRONT_DISTRIBUTION_ID="${{ steps.prepare.outputs.distribution_id }}"
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"
