name: frontend-build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Version"
        required: true

concurrency:
  group: frontend
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag || github.ref }}

      - name: Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Prepare
        id: prepare
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: vite/package-lock.json

      - name: Run
        working-directory: vite
        env:
          VITE_API_ORIGIN: https://${{ vars.DOMAIN }}
          VITE_DISCORD_CLIENT_ID: ${{ vars.DISCORD_CLIENT_ID }}
          VITE_GUILD_INVITE_URL: ${{ vars.GUILD_INVITE_URL }}
          S3_BUCKET: ${{ vars.S3_BUCKET_NAME }}
        run: |
          npm ci
          npm run build
          cd ..
          aws s3 sync vite/dist s3://$S3_BUCKET --delete
